[workspace]
members = [
    "bin",
    "command/*",
    "library/*",
    "tests",
]
resolver = "2"

[profile.dev]
opt-level = 0
debug = true
incremental = true

[profile.dev.package."*"]
opt-level = 2  # optimize dependencies for faster iteration
