[package]
name = "autodomd-command-generate"
version = "0.1.0"
edition = "2021"

[lib]
path = "generate.rs"

[dependencies]
autodomd-library-common = { path = "../../library/common" }
autodomd-library-generator = { path = "../../library/generator" }
