[package]
name = "autodomd-command-scan"
version = "0.1.0"
edition = "2021"

[lib]
path = "scan.rs"

[dependencies]
autodomd-library-common = { path = "../../library/common" }
autodomd-library-scanner = { path = "../../library/scanner" }
autodomd-library-parser = { path = "../../library/parser" }
